//
// ParsedRecipe.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ParsedRecipe: Codable {

    public var title: String?
    public var summary: String?
    public var instructions: String?
    public var image: String?

    public init(title: String?, summary: String?, instructions: String?, image: String?) {
        self.title = title
        self.summary = summary
        self.instructions = instructions
        self.image = image
    }

}
